/**
 * Generates per-package README.md files from the canonical docs MDX so the
 * npm registry view stays in lockstep with what we publish under
 * docs.agentronics.dev. Run via `pnpm sync-readme` (root) or in CI before
 * `changeset publish`.
 */
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(here, '..')
const docsRoot = join(repoRoot, 'apps/docs/content/docs')

interface Section {
  /** Path under apps/docs/content/docs (without .mdx). */
  source: string
  /** Override the H1 emitted before the section. Falls back to MDX title. */
  heading?: string
}

interface PackageReadme {
  pkg: string
  blurb: string
  sections: Section[]
  footerLinks: { label: string; href: string }[]
}

const SHARED_FOOTER: PackageReadme['footerLinks'] = [
  { label: 'Documentation', href: 'https://docs.agentronics.dev' },
  { label: 'Dashboard', href: 'https://dashboard.agentronics.dev' },
  { label: 'Changelog', href: 'https://docs.agentronics.dev/docs/reference/changelog' },
]

const PACKAGES: PackageReadme[] = [
  {
    pkg: 'packages/sdk',
    blurb:
      'Browser SDK for the Agentronics governance layer — detection, auth normalization, policy enforcement, site memory, and trace export for every agent class.',
    sections: [
      { source: 'introduction', heading: 'Why Agentronics' },
      { source: 'getting-started', heading: 'Getting started' },
    ],
    footerLinks: SHARED_FOOTER,
  },
  {
    pkg: 'packages/react',
    blurb:
      'React adapter for the Agentronics SDK. Provides `<AgentronicsProvider>` plus the `useGovernedTool`, `useAgentContext`, and `useSiteMemory` hooks.',
    sections: [
      { source: 'guides/nextjs', heading: 'Next.js integration' },
      { source: 'guides/vite-react', heading: 'Vite + React integration' },
    ],
    footerLinks: SHARED_FOOTER,
  },
  {
    pkg: 'packages/protocol',
    blurb:
      'Wire-format DTOs (Zod schemas + TypeScript types) shared by every Agentronics package. Pinned alongside the SDK release.',
    sections: [{ source: 'reference/configuration', heading: 'Public types' }],
    footerLinks: SHARED_FOOTER,
  },
  {
    pkg: 'packages/gateway',
    blurb:
      'Hono-based gateway service that backs the Agentronics managed control plane. Internal package — operated by Agentronics, not for self-hosting.',
    sections: [
      { source: 'enterprise/deployment-options', heading: 'Deployment options' },
      { source: 'enterprise/data-export', heading: 'Data export' },
    ],
    footerLinks: SHARED_FOOTER,
  },
]

const FRONTMATTER_RE = /^---\n([\s\S]*?)\n---\n?/

const stripFrontmatter = (mdx: string) => {
  const match = mdx.match(FRONTMATTER_RE)
  if (!match) return { body: mdx, title: null as string | null }
  const titleMatch = match[1].match(/^title:\s*(.+)$/m)
  return {
    body: mdx.slice(match[0].length).replace(/^\s*#\s+.+\n+/, ''),
    title: titleMatch ? titleMatch[1].trim() : null,
  }
}

const renderSection = async (section: Section): Promise<string> => {
  const file = join(docsRoot, `${section.source}.mdx`)
  const raw = await readFile(file, 'utf8')
  const { body, title } = stripFrontmatter(raw)
  const heading = section.heading ?? title ?? section.source
  return `## ${heading}\n\n${body.trim()}\n`
}

const renderReadme = async (entry: PackageReadme): Promise<string> => {
  const sections = await Promise.all(entry.sections.map(renderSection))
  const pkgJson = JSON.parse(
    await readFile(join(repoRoot, entry.pkg, 'package.json'), 'utf8')
  ) as { name: string; version: string }

  const header = [
    `# ${pkgJson.name}`,
    '',
    `> ${entry.blurb}`,
    '',
    `**Version:** ${pkgJson.version}`,
    '',
    '<!-- generated by scripts/sync-readme.ts — edit the MDX in apps/docs/content/docs and re-run `pnpm sync-readme` -->',
    '',
  ].join('\n')

  const footer = [
    '## Links',
    '',
    ...entry.footerLinks.map((l) => `- [${l.label}](${l.href})`),
    '',
    '## License',
    '',
    'MIT — © Agentronics.',
    '',
  ].join('\n')

  return `${header}\n${sections.join('\n')}\n${footer}`
}

const run = async () => {
  for (const entry of PACKAGES) {
    const readme = await renderReadme(entry)
    const target = join(repoRoot, entry.pkg, 'README.md')
    await writeFile(target, readme, 'utf8')
    console.log(`✓ wrote ${entry.pkg}/README.md`)
  }
}

run().catch((err) => {
  console.error(err)
  process.exit(1)
})
